export const sectionsData = {
  en: [
    {
      id: 'crash-course',
      label: 'Start Here',
      title: 'Crash Course',
      desc: 'New to data science? A complete overview of the lifecycle — from defining a problem to deploying a model.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Crash Course', tagClass: 'tag-cc',
          title: 'The Data Science Lifecycle',
          desc: 'Seven stages from problem definition to deployment. The end-to-end map before you get into the territory.',
          href: '/crash-course.html', arrow: '→ read',
          spanFull: true,
        },
      ],
    },
    {
      id: 'foundations',
      label: 'Mathematics & Theory',
      title: 'The Foundations',
      desc: 'The math behind every algorithm. No hand-waving — every formula derived step by step with worked examples.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Math', tagClass: 'tag-math',
          title: 'Multiple Linear Regression',
          desc: 'Gradient descent, step by step. Simple regression first, then adding features — same algorithm, one more θ to update.',
          href: '/math/linear_regression.html', arrow: '→ read',
        },
        {
          tag: 'Math', tagClass: 'tag-math',
          title: 'Ordinary Least Squares',
          desc: 'The closed-form solution. Assumptions, diagnostics, strengths, limitations — and when to use it vs gradient descent.',
          href: '/math/ols.html', arrow: '→ read',
        },
        {
          tag: 'Math', tagClass: 'tag-math',
          title: 'R² and Adjusted R²',
          desc: 'How good is your line? SS_total vs SS_res, what R² actually measures, and why Adjusted R² exists.',
          href: '/math/R_R_squared.html', arrow: '→ read',
        },
        {
          tag: 'Math', tagClass: 'tag-math',
          title: 'MSE, MAE & RMSE',
          desc: 'Three error metrics, three personalities. When to use which — and why raw errors cancel to zero.',
          href: '/math/mse_mae_rmse.html', arrow: '→ read',
        },
        {
          tag: 'Math', tagClass: 'tag-math',
          title: 'Underfitting & Overfitting',
          desc: 'The bias-variance tradeoff visualized. Too simple, too complex, and the sweet spot of generalization.',
          href: '/math/overfitting_underfitting.html', arrow: '→ read',
          spanFull: true,
        },
      ],
    },
    {
      id: 'feature-eng',
      label: 'Applied Techniques',
      title: 'Feature Engineering',
      desc: 'Preparing data for models. Every notebook runs end-to-end with real datasets and includes a conclusion with practical guidance.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Feature Eng', tagClass: 'tag-fe',
          title: 'Handling Missing Values',
          desc: 'MCAR, MAR, MNAR. Mean, median, mode imputation — and when to drop vs fill. Titanic dataset walkthrough.',
          href: 'feature_engineering/handling-missing-values.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Feature Eng', tagClass: 'tag-fe',
          title: 'Outlier Detection',
          desc: 'IQR method and the 5-number summary. Box plots for visual detection. When to remove, cap, or investigate.',
          href: 'feature_engineering/outliers.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Feature Eng', tagClass: 'tag-fe',
          title: 'Data Encoding',
          desc: 'One-Hot, Label, and Ordinal Encoding. Sparse vs dense. When each method helps or hurts your model.',
          href: 'feature_engineering/data-encoding.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Feature Eng', tagClass: 'tag-fe',
          title: 'Target Guided Ordinal Encoding',
          desc: 'Encoding high-cardinality categoricals using target means. One column, maximum signal — but watch for leakage.',
          href: 'feature_engineering/target-guided-ordina-encoding.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Feature Eng', tagClass: 'tag-fe',
          title: 'Handling Imbalanced Datasets',
          desc: 'Upsampling, downsampling, and SMOTE. Synthetic minority samples that fill the feature space naturally.',
          href: 'feature_engineering/handling-imbalanced-datasets.ipynb', arrow: '→ notebook',
          spanFull: true,
        },
      ],
    },
    {
      id: 'reference',
      label: 'Quick Reference',
      title: 'Reference Guides',
      desc: 'Bookmark these. Every formula, every metric, every distribution — on a single page.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Reference', tagClass: 'tag-ref',
          title: 'Essential ML Algorithms',
          desc: 'Twelve algorithms that cover ~90% of real-world problems. What each does, when to use it, when to skip it, and a working sklearn implementation.',
          href: '/math/algorithms.html', arrow: '→ open',
        },
        {
          tag: 'Reference', tagClass: 'tag-ref',
          title: 'Formula Cheat Sheet',
          desc: '13 sections from descriptive stats through bias-variance. Every formula you need on one page with sticky navigation.',
          href: '/math/formulas.html', arrow: '→ open',
        },
        {
          tag: 'Stats', tagClass: 'tag-stats',
          title: 'Statistics & Probability Compendium',
          desc: 'The comprehensive reference. Every distribution, every test, every theorem — with formulas, intuition, and when to use each.',
          href: '/math/stats.html', arrow: '→ open',
          spanFull: true,
        },
      ],
    },
  ],

  es: [
    {
      id: 'crash-course',
      label: 'Empieza Aquí',
      title: 'Curso Acelerado',
      desc: '¿Nuevo en ciencia de datos? Un recorrido completo del ciclo de vida — desde definir un problema hasta desplegar un modelo.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Curso Acelerado', tagClass: 'tag-cc',
          title: 'El Ciclo de Vida de la Ciencia de Datos',
          desc: 'Siete etapas desde la definición del problema hasta el despliegue. El mapa completo antes de entrar al territorio.',
          href: '/crash-course.html', arrow: '→ leer',
          spanFull: true,
        },
      ],
    },
    {
      id: 'foundations',
      label: 'Matemáticas y Teoría',
      title: 'Los Fundamentos',
      desc: 'Las matemáticas detrás de cada algoritmo. Sin vaguedades — cada fórmula derivada paso a paso con ejemplos resueltos.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Matemáticas', tagClass: 'tag-math',
          title: 'Regresión Lineal Múltiple',
          desc: 'Descenso de gradiente, paso a paso. Primero regresión simple, luego añadiendo características — el mismo algoritmo, un θ más que actualizar.',
          href: '/math/linear_regression.html', arrow: '→ leer',
        },
        {
          tag: 'Matemáticas', tagClass: 'tag-math',
          title: 'Mínimos Cuadrados Ordinarios',
          desc: 'La solución de forma cerrada. Supuestos, diagnósticos, fortalezas, limitaciones — y cuándo usarlo frente al descenso de gradiente.',
          href: '/math/ols.html', arrow: '→ leer',
        },
        {
          tag: 'Matemáticas', tagClass: 'tag-math',
          title: 'R² y R² Ajustado',
          desc: '¿Qué tan buena es tu línea? SS_total vs SS_res, qué mide realmente R², y por qué existe el R² Ajustado.',
          href: '/math/R_R_squared.html', arrow: '→ leer',
        },
        {
          tag: 'Matemáticas', tagClass: 'tag-math',
          title: 'MSE, MAE y RMSE',
          desc: 'Tres métricas de error, tres personalidades. Cuándo usar cada una — y por qué los errores crudos se cancelan a cero.',
          href: '/math/mse_mae_rmse.html', arrow: '→ leer',
        },
        {
          tag: 'Matemáticas', tagClass: 'tag-math',
          title: 'Subajuste y Sobreajuste',
          desc: 'El equilibrio sesgo-varianza visualizado. Demasiado simple, demasiado complejo, y el punto óptimo de generalización.',
          href: '/math/overfitting_underfitting.html', arrow: '→ leer',
          spanFull: true,
        },
      ],
    },
    {
      id: 'feature-eng',
      label: 'Técnicas Aplicadas',
      title: 'Ingeniería de Features',
      desc: 'Preparando datos para modelos. Cada notebook se ejecuta de principio a fin con conjuntos de datos reales e incluye una conclusión con orientación práctica.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Ing. Features', tagClass: 'tag-fe',
          title: 'Manejo de Valores Faltantes',
          desc: 'MCAR, MAR, MNAR. Imputación por media, mediana, moda — y cuándo eliminar vs rellenar. Recorrido con el conjunto de datos Titanic.',
          href: 'feature_engineering/handling-missing-values.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Ing. Features', tagClass: 'tag-fe',
          title: 'Detección de Valores Atípicos',
          desc: 'Método IQR y el resumen de 5 números. Diagramas de caja para detección visual. Cuándo eliminar, limitar o investigar.',
          href: 'feature_engineering/outliers.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Ing. Features', tagClass: 'tag-fe',
          title: 'Codificación de Datos',
          desc: 'Codificación One-Hot, por Etiquetas y Ordinal. Dispersa vs densa. Cuándo cada método ayuda o perjudica a tu modelo.',
          href: 'feature_engineering/data-encoding.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Ing. Features', tagClass: 'tag-fe',
          title: 'Codificación Ordinal Guiada por Objetivo',
          desc: 'Codificando categóricas de alta cardinalidad usando medias objetivo. Una columna, señal máxima — pero cuidado con la fuga de datos.',
          href: 'feature_engineering/target-guided-ordina-encoding.ipynb', arrow: '→ notebook',
        },
        {
          tag: 'Ing. Features', tagClass: 'tag-fe',
          title: 'Manejo de Conjuntos Desequilibrados',
          desc: 'Sobremuestreo, submuestreo y SMOTE. Muestras sintéticas de la minoría que llenan el espacio de características naturalmente.',
          href: 'feature_engineering/handling-imbalanced-datasets.ipynb', arrow: '→ notebook',
          spanFull: true,
        },
      ],
    },
    {
      id: 'reference',
      label: 'Referencia Rápida',
      title: 'Guías de Referencia',
      desc: 'Márcalos. Cada fórmula, cada métrica, cada distribución — en una sola página.',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'Referencia', tagClass: 'tag-ref',
          title: 'Algoritmos Esenciales de ML',
          desc: 'Doce algoritmos que cubren ~90% de los problemas reales. Qué hace cada uno, cuándo usarlo, cuándo evitarlo, y una implementación funcional en sklearn.',
          href: '/math/algorithms.html', arrow: '→ abrir',
        },
        {
          tag: 'Referencia', tagClass: 'tag-ref',
          title: 'Hoja de Referencia de Fórmulas',
          desc: '13 secciones desde estadística descriptiva hasta sesgo-varianza. Cada fórmula que necesitas en una página con navegación fija.',
          href: '/math/formulas.html', arrow: '→ abrir',
        },
        {
          tag: 'Estadística', tagClass: 'tag-stats',
          title: 'Compendio de Estadística y Probabilidad',
          desc: 'La referencia completa. Cada distribución, cada prueba, cada teorema — con fórmulas, intuición y cuándo usar cada uno.',
          href: '/math/stats.html', arrow: '→ abrir',
          spanFull: true,
        },
      ],
    },
  ],

  ja: [
    {
      id: 'crash-course',
      label: 'ここから始める',
      title: '速習コース',
      desc: 'データサイエンスが初めて？問題の定義からモデルのデプロイまで — ライフサイクルの完全な概要。',
      gridClass: 'grid-2',
      cards: [
        {
          tag: '速習コース', tagClass: 'tag-cc',
          title: 'データサイエンスのライフサイクル',
          desc: '問題定義からデプロイまでの7段階。領域に入る前のエンドツーエンドのマップ。',
          href: '/crash-course.html', arrow: '→ 読む',
          spanFull: true,
        },
      ],
    },
    {
      id: 'foundations',
      label: '数学と理論',
      title: '基礎',
      desc: 'すべてのアルゴリズムの背景にある数学。曖昧さなし — すべての数式が段階的に導出され、解説例付き。',
      gridClass: 'grid-2',
      cards: [
        {
          tag: '数学', tagClass: 'tag-math',
          title: '重回帰分析',
          desc: '勾配降下法、ステップバイステップ。まず単回帰、次に特徴量追加 — 同じアルゴリズム、もう一つのθを更新。',
          href: '/math/linear_regression.html', arrow: '→ 読む',
        },
        {
          tag: '数学', tagClass: 'tag-math',
          title: '普通最小二乗法',
          desc: '閉じた形の解。仮定、診断、強み、限界 — そして勾配降下法との使い分け。',
          href: '/math/ols.html', arrow: '→ 読む',
        },
        {
          tag: '数学', tagClass: 'tag-math',
          title: 'R²と調整済みR²',
          desc: 'あなたの直線はどれくらい良い？SS_total vs SS_res、R²が実際に何を測定するか、そして調整済みR²が存在する理由。',
          href: '/math/R_R_squared.html', arrow: '→ 読む',
        },
        {
          tag: '数学', tagClass: 'tag-math',
          title: 'MSE、MAEとRMSE',
          desc: '3つの誤差指標、3つの個性。どれをいつ使うか — そして生の誤差がゼロになる理由。',
          href: '/math/mse_mae_rmse.html', arrow: '→ 読む',
        },
        {
          tag: '数学', tagClass: 'tag-math',
          title: '過少適合と過学習',
          desc: 'バイアス-分散トレードオフの視覚化。単純すぎる、複雑すぎる、そして汎化の最適点。',
          href: '/math/overfitting_underfitting.html', arrow: '→ 読む',
          spanFull: true,
        },
      ],
    },
    {
      id: 'feature-eng',
      label: '応用技術',
      title: '特徴量エンジニアリング',
      desc: 'モデルのためのデータ準備。すべてのノートブックはリアルデータセットでエンドツーエンドで実行され、実践的なガイダンスを含む結論が含まれています。',
      gridClass: 'grid-2',
      cards: [
        {
          tag: '特徴量エンジニアリング', tagClass: 'tag-fe',
          title: '欠損値の処理',
          desc: 'MCAR、MAR、MNAR。平均、中央値、最頻値の補完 — そして削除vs補填の判断。タイタニックデータセットのウォークスルー。',
          href: 'feature_engineering/handling-missing-values.ipynb', arrow: '→ ノートブック',
        },
        {
          tag: '特徴量エンジニアリング', tagClass: 'tag-fe',
          title: '外れ値検出',
          desc: 'IQR法と5数要約。視覚的検出のためのボックスプロット。削除、上限設定、調査のいずれにするか。',
          href: 'feature_engineering/outliers.ipynb', arrow: '→ ノートブック',
        },
        {
          tag: '特徴量エンジニアリング', tagClass: 'tag-fe',
          title: 'データエンコーディング',
          desc: 'One-Hot、ラベル、序数エンコーディング。スパースvs密。各手法がモデルを助けるか妨げるか。',
          href: 'feature_engineering/data-encoding.ipynb', arrow: '→ ノートブック',
        },
        {
          tag: '特徴量エンジニアリング', tagClass: 'tag-fe',
          title: '目標誘導序数エンコーディング',
          desc: '目標平均を使った高基数カテゴリのエンコード。1列で最大シグナル — ただしリークに注意。',
          href: 'feature_engineering/target-guided-ordina-encoding.ipynb', arrow: '→ ノートブック',
        },
        {
          tag: '特徴量エンジニアリング', tagClass: 'tag-fe',
          title: '不均衡データセットの処理',
          desc: 'アップサンプリング、ダウンサンプリング、SMOTE。特徴空間を自然に満たす合成少数サンプル。',
          href: 'feature_engineering/handling-imbalanced-datasets.ipynb', arrow: '→ ノートブック',
          spanFull: true,
        },
      ],
    },
    {
      id: 'reference',
      label: 'クイックリファレンス',
      title: 'リファレンスガイド',
      desc: 'ブックマークしてください。すべての数式、すべての指標、すべての分布 — 1ページに。',
      gridClass: 'grid-2',
      cards: [
        {
          tag: 'リファレンス', tagClass: 'tag-ref',
          title: '必須の機械学習アルゴリズム',
          desc: '実世界の問題の約90%をカバーする12のアルゴリズム。何をし、いつ使い、いつ避け、sklearnでどう動かすか。',
          href: '/math/algorithms.html', arrow: '→ 開く',
        },
        {
          tag: 'リファレンス', tagClass: 'tag-ref',
          title: '数式チートシート',
          desc: '記述統計からバイアス-分散まで13セクション。スティッキーナビゲーション付きの1ページに必要なすべての数式。',
          href: '/math/formulas.html', arrow: '→ 開く',
        },
        {
          tag: '統計', tagClass: 'tag-stats',
          title: '統計・確率コンペンディウム',
          desc: '包括的なリファレンス。すべての分布、すべての検定、すべての定理 — 数式、直感、使い分け付き。',
          href: '/math/stats.html', arrow: '→ 開く',
          spanFull: true,
        },
      ],
    },
  ],
};
